// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StayFit.Infrastructure.Data;

#nullable disable

namespace StayFit.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424000000_AddSecurityLogEntry")]
    partial class AddSecurityLogEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a partial migration file. The full snapshot should be regenerated using:
            // dotnet ef migrations add AddSecurityLogEntry
            
#pragma warning restore 612, 618
        }
    }
}
